### ISSUE TITLE
[Feature] Add back sticky counter to MemberCount

### ISSUE THREAD

**Issue by Dyskal** [Arashiryuu/crap#109]
**Which plugin is this about?**
MemberCount

**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like**
Adds CSS to always position the counter atop the member list, regardless of scroll.

**Additional context**
Was here before 2.2.0 (I don't remember the exact version)

**Comment by Arashiryuu** [comment]
That setting was removed due to changes made to the plugin that force it to do that always.
