### ISSUE TITLE
Settings fail to load

### ISSUE THREAD

**Issue by Eggtooth** [Arashiryuu/crap#11]
Each time I am attempting to start discord, I have "settings do not exist or are unable to be loaded". It happened after latest commit. Deleting settings file, re-creating it from scratch didn't solve it.

**Comment by Arashiryuu** [comment]
I rewrote how the plugin manages data to be more robust so older configs will be invalid now, I also updated the plugin again earlier which fixes the load issue.

Is the scrolling issue related to the member-list perhaps? As I believe I may have fixed that also with my most recent commit.

**Comment by Eggtooth** [comment]
The scrolling issue is still there sadly. Scrolling down (away from hidden user), then scrolling up reveals them again.

**Comment by Arashiryuu** [comment]
I don't have that issue, and the current version is identical to my file, sometimes I push updates without changing the version number so try redownloading and see if it still occurs.
