### ISSUE TITLE
[Bug] MemberCount doesn't work properly even after update

### ISSUE THREAD

**Issue by baszin** [Arashiryuu/crap#110]
**Which plugin is this about?**
MemberCount

**Describe the Bug**
The text background is in some themes in Discord's color palette.

**To Reproduce**
Try a theme with the plugin

**Expected Behavior**
The text background should be in the same color palette as the theme.

**Screenshots**
![image](https://user-images.githubusercontent.com/64983641/112689051-0a022880-8e7a-11eb-9bb2-932f1922d74d.png)

**Discord Version**
Stable

**Additional Context**
The theme I'm using is Nocturnal v2.6.1 by Spectra#7698, this issue should be fixed but it isn't. In some other themes the plugin works or doesn't work properly.

For example Frosted Glass by Gibbu#1211 doesn't work properly as a transparent box is visible
![image](https://user-images.githubusercontent.com/64983641/112689225-47ff4c80-8e7a-11eb-8406-f27f23627060.png)

Shouldn't removing the box solve the issue?

**Comment by Arashiryuu** [comment]
Theme compatibility should be handled by the theme itself, ask your theme author to update it if the theme had previously accomodated the plugin, or request they do accomodate it, alternatively you can ask for some custom css to blend it yourself.
