### ISSUE TITLE
Component Issue

### ISSUE THREAD

**Issue by mighelce** [Arashiryuu/crap#114]
![InkedScreenshot_3_LI](https://user-images.githubusercontent.com/58997332/115223273-fbf2a100-a0e1-11eb-81e2-a1b08e935a47.jpg)
This is has been happening to me :p i don't know what to do. I guess i need this plugin to be alive because it's great :D

**Comment by BennyExtreme** [comment]
Yesterday I had the same problem, try to uninstall BetterDiscord and make sure to reinstall it from [here](https://github.com/BetterDiscord/Installer/releases/), it worked for me.
