### ISSUE TITLE
Component error showing when enabled

### ISSUE THREAD

**Issue by chaoticbeatz** [Arashiryuu/crap#115]
In case you arent aware on it, a few days ago i had an issue where in place of the member count it widened the server member area and put component error at the top in place of where the member count would have been at as shown in screenshot that is at [this screenshot](https://prnt.sc/11sdyc4) making the plugin unable to be used. i am unaware as to how many other people would be having this issue as i am the only one that im aware of in all the servers im in that arent specific to programming that uses this plugin.

**Comment by Arashiryuu** [comment]
Someone else had that and made an issue before you.

With such a lack of any critical information beyond knowing this is happening my suggestion is following the advice from the previous issue thread.

https://github.com/Arashiryuu/crap/issues/114#issuecomment-823148237
