### ISSUE TITLE
[Feature] Please add theme support

### ISSUE THREAD

**Issue by raffel080108** [Arashiryuu/crap#116]
**Which plugin is this about?**

 MemberCount
**Is your feature request related to a problem? Please describe.**

Not really. It is only weird having the default discord background just sitting right there

**Describe the feature you'd like**

I would like to have theme support, it always uses the default discord background in the section where it lists the server members

**Additional context**

**Comment by Arashiryuu** [comment]
This is a theme-by-theme cases type of issue for actual compatibility and not some shoddy generalized band-aid fix - if a theme wants to support the plugin then it can.

**Comment by raffel080108** [comment]
I use ClearVision as Theme - It is very adoptive and support pretty much every plugin that I know/exist for BetterDiscord. I think it's not, that the Theme does not support certain plugins, but your plugin does not adopt themes, it always uses the default discord background, so it's a problem on your side and not from the Theme

**Comment by Arashiryuu** [comment]
"It is very adoptive and support pretty much every plugin that I know/exist for BetterDiscord." - Evidently not.

How my plugin determines background color is the same way Discord does, so if my plugin isn't matching your theme, then your theme is doing something to cause that mismatch; the theme is responsible for handling its own mistake.

If you'd like, I can provide you some css to handle your issue, but it is by no means a plugin fault.
