### ISSUE TITLE
[Bug] HideServerChannelRedux

### ISSUE THREAD

**Issue by HL3000** [Arashiryuu/crap#117]
**Which plugin is this about?**
HideServersChannelsRedux

**Describe the Bug**
Doesn't close or reopen sometimes.

**To Reproduce**
Happens randomly, the issue might be with me resizing Discord itself

**Expected Behavior**
Open and close on button click.

**Discord Version**
 Canary

**Comment by Arashiryuu** [comment]
idk if this is still a problem but I'm closing it
