### ISSUE TITLE
Minimal mode breaks toggling channels

### ISSUE THREAD

**Issue by blakeleftwich** [Arashiryuu/crap#119]
**Which plugin is this about?**
HideServersChannelsRedux.plugin

**Describe the Bug**
When I toggle the hide channels and/or hide servers button, a gap is left where they were.

**To Reproduce**
Check minimal mode, then click hide servers or hide channels button

**Expected Behavior**
Hide without leaving a gap

**Screenshots**
![image](https://user-images.githubusercontent.com/40797870/118834475-3e99cb80-b890-11eb-86f9-ef963d816322.png)
![image](https://user-images.githubusercontent.com/40797870/118834618-57a27c80-b890-11eb-874a-ae35c08b9224.png)
![image](https://user-images.githubusercontent.com/40797870/118834722-69841f80-b890-11eb-9ac8-ee7b2d7c267d.png)

**Discord Version**
Stable 85277 (3508014)
BetterDiscord 1.1.0

**Additional Context**
If I uncheck width parameter in style, the issue is fixed, but I have to do that every time I open Discord.

Thank you for the great plugin! :)

**Comment by dreadbalaur** [comment]
Thanks for making the thread! I was scrambling my head for the entire day because of this. I think I can live without minimal mode until this issue gets fixed.

**Comment by blakeleftwich** [comment]
Thank you! The dev very generously walked me through the process and we
discovered this bug together. They suggested that I submit it. :)
