### ISSUE TITLE
[Feature] - Member count: online count

### ISSUE THREAD

**Issue by Dschogo** [Arashiryuu/crap#125]
**Which plugin is this about?**
Member count

**Describe the feature you'd like**
it would be nice to extend its functionality if it is possible by the online count.

Something like : MEMBERS - 375 (1345)  [in brackets the total members and before it the online count]

**Additional context**
Hey awesome plugin :D

Toggleable as plugin settings?

**Comment by dav1312** [comment]
![image](https://user-images.githubusercontent.com/63931154/124597731-1a0baa00-de64-11eb-9f6b-f9416f1e6708.png)

**Comment by Dschogo** [comment]
@dav1312 How did u got that? Is that ontop of the member list like the couner?

**Comment by dav1312** [comment]
> @dav1312 How did u got that? Is that ontop of the member list like the counter?

@Dschogo It's Total Members, a PowerCord plugin

**Comment by Dschogo** [comment]
Hmm okey, using BD. Maybe thats a good "reference" on which Arashiryuu could improve this plugin.
