### ISSUE TITLE
[Bug] Unable to copy ID

### ISSUE THREAD

**Issue by DyteSprite** [Arashiryuu/crap#128]
**Which plugin is this about?**

ChatUserIDsRedux.plugin.js

**Describe the Bug**

Unable to copy ID after double clicking ID ("Failed to copy! See console for error(s)!"). In the console the error is shortly described as "[ChatUserIDsRedux] DOMException: Write permission denied." The full error is as follows- [https://i.gyazo.com/5080dda94fa470abf8701a0ba8102089.png](url)

**To Reproduce**

Be on the most recent version of Discord Canary and have the plugin on latest version.

**Expected Behavior**

To be able to successfully copy the ID.

**Screenshots**

[https://i.gyazo.com/8d2de0293c7bd2af443e0e355a9e0f37.png](url)
[https://i.gyazo.com/5080dda94fa470abf8701a0ba8102089.png](url)

**Discord Version**

Canary 87139 (c16d9c5)
Host 1.0.35
Windows 10 64-Bit (10.0.19043)
Powercord v2 (00f3d03)

**Additional Context**

I use this plugin in combination with Powercord and BDcompact (which allows the running of BD plugins on Powercord); therefore, I am not sure if this issue exists on other versions of Discord.

**Comment by tort-oise** [comment]
Is this still unfixed?

**Comment by DyteSprite** [comment]
I am unable to verify if this exact issue still occurs, as the ID tag currently does not appear next to the name at all with the following Discord version: "Canary 108338 (99e649d) Host 1.0.42 Windows 10 64-Bit (10.0.19043)" and plugin version v1.0.21.

**Comment by tort-oise** [comment]
![image](https://user-images.githubusercontent.com/81963124/146432110-f9c4fd51-15f0-4f95-8f99-0f6da2baa81b.png)
It seems to work for me, using the exact same version of Canary and the plugin, and 19043.1348 of Windows 10 Home.

**Comment by tort-oise** [comment]
![image](https://user-images.githubusercontent.com/81963124/146432400-e296f5b3-56bd-4021-b66e-f13b63138346.png)
The only thing I can complain about is the color feature being gone. Although, somehow, this same exact thing applies to normal Discord as well. Kind of weird, as this plugin is listed as specifically having color support.

**Comment by tort-oise** [comment]
Although, to note, I'm using vanilla BD for testing this. It might be a powercord thing. I'll complain about the colors later though.

**Comment by tort-oise** [comment]
Well, I just tried it with PowerCord, and.... It works fine. The IDs look a bit off, but the color function _works_ now too for some reason. I'd actually say it works **better**. Are you _sure_ you're using the latest of everything, and doing everything right?

**Comment by tort-oise** [comment]
Maybe check if there's some other plugin causing it.

**Comment by DyteSprite** [comment]
Sorry for the late reply. After an extensive amount of plugin testing, it seems that the culprit is in-fact another plugin, but specifically a powercord plugin and not a BD one. The culprit plugin in question is "better-status-indicators", which can be found [here](https://github.com/GriefMoDz/better-status-indicators). Currently, if you load Canary with C.U.I.D.R disabled, and then later enable B.S.I., CUIDR will work fine, until you restart Canary, then it will not work until you've disabled BSI and reload again. If possible, maybe you'd be able to fix the incompatibility issues with this, but if not, I totally understand, and can close the ticket.

**Comment by tort-oise** [comment]
Well, since this isn't a PowerCord plugin, I would doubt it, but there's a chance.
