### ISSUE TITLE
[BUG] ChatUserIDsRedux `white-space` css breaks ChannelPermissions

### ISSUE THREAD

**Issue by Farcrada** [Arashiryuu/crap#131]
**Which plugin is this about?**
ChatUserIDsRedux 

**Describe the Bug**
See issue: https://github.com/Farcrada/DiscordPlugins/issues/30
Location: https://github.com/Arashiryuu/crap/blob/bae85338e7bd7070bc27533f3383e4143b0d359f/ToastIntegrated/ChatUserIDsRedux/ChatUserIDsRedux.plugin.js#L277

**To Reproduce**
ChannelPermissions and ChatUserIDsRedux enabled.

**Screenshots**
See issue.

**Discord Version**
Stable

**Additional Context**
In my personal testing I have not seen an issue with that CSS block removed; is it a remnant?

My tooltip uses the `.tooltip-2QfLtc` class.

**Comment by Arashiryuu** [comment]
Just override it in your own plugin's css?

**Comment by Farcrada** [comment]
> 
> 
> That line is for formatting purposes - when you hover a user's id tag in chat it displays a tooltip, though that tooltip is a toggleable setting.
I saw that, but in my testing keeping that css block in or not had no effect on any formatting present. Hence my wondering if this was a remnant and (maybe) not needed anymore.

**Comment by Farcrada** [comment]
It also breaks the formatting of the title bar. 
Normal:
![image](https://user-images.githubusercontent.com/8385001/123007814-4f66c100-d3a9-11eb-9e87-aa9b3beabf5d.png)

With ChatUserIDsRedux:
![image](https://user-images.githubusercontent.com/8385001/123007794-44ac2c00-d3a9-11eb-9569-5862150af00f.png)
