### ISSUE TITLE
[Bug] Incompatible with DateViewer plugin

### ISSUE THREAD

**Issue by RedCMD** [Arashiryuu/crap#133]
**Which plugin is this about?**
[DateViewer](https://github.com/hammy1/BDStuff/tree/master/Plugins/dateViewer) by hammy

**Describe the Bug**
MemberCount causes DateViewer to no longer display the date in the bottom right coner of the app
But instead a blank gray section is left behind

**To Reproduce**
Install and enable both DateViewer and MemberCount at the same time

**Expected Behavior**
Date is shown in bottom right coner

**Screenshots**
![image](https://user-images.githubusercontent.com/33529441/124449457-973d0d80-ddd7-11eb-9c2e-9d3fa9449bef.png)
![image](https://user-images.githubusercontent.com/33529441/124449470-999f6780-ddd7-11eb-8f65-bd396b6e4ead.png)

**Discord Version**
Stable

**Other**
DateViewer bug report: https://github.com/hammy1/BDStuff/issues/17

**Comment by Arashiryuu** [comment]
Made changes to my plugin, and created a PR for DateViewer to fix it.
