### ISSUE TITLE
[Bug] the whole thing doesnt work lol

### ISSUE THREAD

**Issue by fragmentofgaming** [Arashiryuu/crap#134]
the member count thing lol
just doesn't work

**Describe the Bug**
lol

**To Reproduce**
literally use the plugin on ptb or canary

**Expected Behavior**
the thing breaks

**Screenshots**
https://imgur.com/a/xE7oBpS

ptb and canary the new update breaks it somehow I think

**Comment by takos22** [comment]
I have the same bug

**Comment by MrConorAE** [comment]
Yep, same here on stable.
Stable build 91036 (3507a4c), BetterDiscord 1.2.0

**Comment by hyperwave11** [comment]
Can confirm

**Comment by ColonelGerdauf** [comment]
I can confirm as well. I am investigating the code to see where the issue is in relation to the discord updates

**Comment by MennoGamed** [comment]
Can confirm, on stable discord.
