### ISSUE TITLE
[Bug] LineNumbersRedux not working

### ISSUE THREAD

**Issue by KaKi87** [Arashiryuu/crap#136]
**Which plugin is this about?**
LineNumbersRedux

**Describe the Bug**
The plugin does not work at all, i.e. it never adds line numbers to code blocks.

**To Reproduce**
Install LineNumbersRedux

**Expected Behavior**
The plugin works perfectly, i.e. it adds line numbers to code blocks.

**Screenshots**
Unnecessary

**Discord Version**
Stable

**Additional Context**
None

---
Thanks

**Comment by Arashiryuu** [comment]
use [BetterCodeblocks](https://betterdiscord.app/plugin/BetterCodeblocks) instead.

**Comment by KaKi87** [comment]
BetterCodeBlocks generates other issues, I prefer how LineNumbersRedux was adding line numbers without changing anything else to the codeblock element

![2021-08-07 16_10_58-dev - Discord](https://user-images.githubusercontent.com/21284089/128603081-0bebd11c-fa74-4a9b-84d4-5e42fc373860.png)
