### ISSUE TITLE
[Bug] - DisplayServersAsChannels breaks HideServersChannelsRedux

### ISSUE THREAD

**Issue by Hate9** [Arashiryuu/crap#137]
**Which plugin is this about?**
HideServersChannelsRedux

**Describe the Bug**
When both [DisplayServersAsChannels](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/DisplayServersAsChannels) and [HideServersChannelsRedux](https://github.com/Arashiryuu/crap/tree/master/ToastIntegrated/HideServersChannelsRedux) are installed, clicking HideServersChannelsRedux's "Toggle Servers" button hides the server list content, but does not hide the box containing the list. This does not occur without DisplayServersAsChannels installed and active.

**To Reproduce**
Install DisplayServersAsChannels and HideServersChannelsRedux; click on the "Toggle Servers" button while in a server.

**Expected Behavior**

**Discord Version**
Stable

**Additional Context**
[A video of the issue in action.](https://drive.google.com/file/d/1PpS6oraWOebAlZv_8Rpr_-2tB2lBuazM/view?usp=sharing) Please note that, although the panel briefly appears to be properly gone, this only occurs extremely briefly, immediately after *showing* the panel.
Also posted to [mwittrien/DisplayServersAsChannels](https://github.com/mwittrien/BetterDiscordAddons/issues/1056).

**Comment by mwittrien** [comment]
Fixed it but HideServersChannelsRedux really should use !important

**Comment by Arashiryuu** [comment]
> Fixed it but HideServersChannelsRedux really should use !important

nah, Discord doesn't have an inline style on anything the plugin touches so it doesn't have any reason to use `!important`
