### ISSUE TITLE
[Bug] Channels hiding and unhiding themselves.

### ISSUE THREAD

**Issue by PapaSmurf-ML64** [Arashiryuu/crap#140]
**Which plugin is this about?**
HideUtils

**Describe the Bug**
Channel not intended to be hidden hides itself upon scrolling to a certain point.

**To Reproduce**
Scrolling up and down the channel list

**Expected Behavior**
The channel should not be hiding.

**Screenshots**
![Peek 2021-08-28 10-53](https://user-images.githubusercontent.com/4394814/131226873-6b860168-75e5-4f93-bdfb-9f633484cd73.gif)

**Discord Version**
Stable

**Additional Context**
The channel in the screenshot is the only one I've noticed this bug with.
[discord.com-1630173502723.log](https://github.com/Arashiryuu/crap/files/7071198/discord.com-1630173502723.log)

**Comment by Arashiryuu** [comment]
Repeat of #80
