### ISSUE TITLE
[Bug] Self-hide the stage channel and the Plugin Settings Dialog is displayed in the background

### ISSUE THREAD

**Issue by thanhgaming5550** [Arashiryuu/crap#144]
**Which plugin is this about?**
HideUtils

**Describe the Bug**
1) Self-hide the stage channels while I don't set to hide it
2) Channels hidden in Plugin Settings are displayed behind Plugin Settings

**To Reproduce**
1) View the channel list on the community server with theatrical channel
2) Go to Plugin Settings and choose 1 of 5 items there

**Expected Behavior**
1) Stage channel is not hidden
2) The dialog box popped up right in front of me

[**Video**](https://streamable.com/xpzf8p)

**Discord Version**
Stable 96885 (53fd6d6)

**Additional Context**
no

**Comment by ToxykAuBleu** [comment]
Same bug !

**Comment by Arashiryuu** [comment]
1 - repeat of issue #80 
2 - fixed
