### ISSUE TITLE
[Bug] Duplicate HideUtils and HideServersChannelsRedux enabled/disabled notifications.

### ISSUE THREAD

**Issue by WildSnail913** [Arashiryuu/crap#146]
**Plugins:**
HideUtils v2.1.46
HideServersChannelsRedux v1.1.11

**Describe the Bug**
Enabling and disabling HideUtils or HideServersChannelsRedux cause a second popup behind the first.

**To Reproduce**
Toggle HideUtils or HideServersChannelsRedux on or off.

**Expected Behavior**
A single popup box like other plugins.

**Screenshots**
![image](https://user-images.githubusercontent.com/83524145/134755466-396995bc-0356-42ec-b467-5725242daf25.png)

**Discord Version**
[BUILD INFO] Release Channel: stable, Build Number: 99016, Version Hash: 0d5a8015643301b0ff152c8a05f59a358af50792

**Comment by Arashiryuu** [comment]
These plugins have been creating their own toasts since before BD had its own option for toasts, you can disable the second one from the `General` tab in BD Settings
