### ISSUE TITLE
[Feature] Add French translation to Member Count

### ISSUE THREAD

**Issue by MaximeDawn** [Arashiryuu/crap#156]
**Which plugin is this about?**
Member Count

**Is your feature request related to a problem? Please describe.**
French translation is missing, and could be great and easy to add.

**Describe the feature you'd like**
Have the strings in French

**Additional context**
[EDIT] : Did this myself after the "en" strings and works great.
```
fr: {
  INCLUDE: 'Inclure le serveur',
  EXCLUDE: 'Exclure le serveur',
  MEMBERS: 'Membres'
}
```

**Comment by tort-oise** [comment]
I created a PR (#157), with your translation.
