### ISSUE TITLE
Hide Utils - users not hidden from chat, only list.

### ISSUE THREAD

**Issue by Eggtooth** [Arashiryuu/crap#16]
So for some reason when hiding certain user in latest discord version, they still display in chat, despite being hidden on the user list on the right.. I can't also hide them by right clicking their name in chat as there's no "Hide User", and have to manually scroll on the user list to add them.. and yet it still doesn't hide them from chat itself, only from the list.

**Comment by Arashiryuu** [comment]
That's a result of Discord's recent update, it changed class names for the chat and internally restructured some things.

Fixed, update to version 1.1.9.

**Comment by Eggtooth** [comment]
<3 thank you
