### ISSUE TITLE
[Bug] HideUtils no right click option available

### ISSUE THREAD

**Issue by JustCryen** [Arashiryuu/crap#161]
**Which plugin is this about?**
HideUtils v2.1.53

**Describe the Bug**
Plugin disappeared from the right click menu (everywhere: chat, voicechat, servers)
Previously hidden entries are still hidden, this just prevents me from adding more.

Also, in the plugin settings I'm unable to select which settings I would like to visit.
This makes me unable to remove already hidden channels from the gui (unless I disable the plugin of course)

I tried to remove the config.json but it doesn't "unlock" the plugin from this state, it just makes the changes to the hidden channels (so config is probably not the issue)
I still can't show / hide channels / servers and so on.
And yes, I restarted Discord after this.

One important thing to mention.
Some of the servers I've hidden have emojis…

**To Reproduce**
This is a tough one, I'm not sure.
It just happened some time ago and I thought it was more widespread and someone already reported it…
It probably happened after an update.

**Expected Behavior**
Right clicking on a channel / chat / […] should give me the option to hide it.
Also, in settings, making the "settings selection" should bring up a popup with already hidden stuff.

**Screenshots**
![image](https://user-images.githubusercontent.com/41633661/150574213-5ac6fd04-d1b3-4074-a33b-a60e546c21bb.png)

**Discord Version**
PTB

**Additional Context**
OS: ArchLinux
Ptb 111534 (dbae6d3)
BetterDiscord 1.3.0
Host 0.0.28 Linux 64-Bit (5.16.1-Zen1-1-Zen)

**Comment by mahesapndu** [comment]
I'm on HideUtils v2.1.53 with Better Discord v1.4.0 and same things happened. It seems the plugin stopped working for some reason.

**Comment by JustCryen** [comment]
![image](https://user-images.githubusercontent.com/41633661/150991447-66f655cb-610e-4a1a-8639-ad9c40d2d223.png)
I can confirm, thanks Arashiryuu!
