### ISSUE TITLE
HideUtils New Message in Server Not Showing Properly[Bug] 

### ISSUE THREAD

**Issue by ClickyOSU** [Arashiryuu/crap#162]
**Which plugin is this about?**
HideUtils v2.1.54

**Describe the Bug**
Whenever a new message is added to a server/channel and you swap to it it will position you far above where the actually new message is earlier on in the chat.

**To Reproduce**
Type in another discord, and open up the channel with the new message alert.

**Expected Behavior**
Just to show the newest message right away however it can go up to 10-30 minutes in the past.

**Discord Version**
Stable

**Comment by a1termoon** [comment]
Yes, same. HideUtils remove "NEW redline", and when open any channel you show up god knows where, annoying.

**Comment by lolpowerluke** [comment]
also hides this line
![image](https://user-images.githubusercontent.com/47672899/151709197-ae6b05e6-6f66-4ee1-a8a2-e9356ea62cc7.png)

**Comment by gtm-nayan** [comment]
Commenting out `patchMessages` fixes the issue at hand but opens up a flurry of others. Hopefully that'd help narrow it down nonetheless.

**Comment by Arashiryuu** [comment]
> Commenting out `patchMessages` fixes the issue at hand but opens up a flurry of others. Hopefully that'd help narrow it down nonetheless.

disabling part of the hiding functionality is not a "fix"

**Comment by gtm-nayan** [comment]
I wouldn't say it is either, could've prolly worded it better. Still, it could be used as a temporary workaround depending on what someone is using the plugin for, eg. just hiding a user from the members sidebar.

**Comment by Arashiryuu** [comment]
`2.1.55` restores those dividers, and may possibly have helped with the message jumping issue, will keep the thread open to monitor that.

**Comment by ezeholz** [comment]
I've been using this for a week now, and for the most part seems to be working. However, HideUtils crash my discord every time I enter a chat where this apears:
![image](https://user-images.githubusercontent.com/30635862/152716914-403c5c90-5c24-498c-9716-af85a801448e.png)

The following is showing in console right after crash:
![image](https://user-images.githubusercontent.com/30635862/152717065-590c372e-d5c6-4231-87aa-bcf260d3f176.png)
![image](https://user-images.githubusercontent.com/30635862/152717103-36379e6b-a8af-44bd-9701-67e71673ba15.png)
![image](https://user-images.githubusercontent.com/30635862/152717130-3460d8b3-70df-460e-a61f-0abb680b8937.png)
