### ISSUE TITLE
Member Count Doesn't Work Well With Themes

### ISSUE THREAD

**Issue by Tristanmerkley** [Arashiryuu/crap#167]
**Which plugin is this about?**
Member Count

**Is your feature request related to a problem? Please describe.**
Doesn't work well when using a theme, as it creates a big grey box.

**Describe the feature you'd like**
For the count area to not make a big grey box and work with themes, such as making it transparent instead of grey.

**Additional context**
Previous/current look with themes:
![image](https://user-images.githubusercontent.com/90348406/151739602-ec46a8b8-442e-47b2-b68e-3c196a1f13cb.png)
![image](https://user-images.githubusercontent.com/90348406/151740513-b4f0d3af-f194-43a0-9efa-3bd3ecce9bc0.png)
Fixed/proposal:
I changed the background to be transparent and changed the top margin to padding, so it had the same transparency as set in the theme, plus I got rid of the bottom border.
![image](https://user-images.githubusercontent.com/90348406/151739343-083f13d6-3702-49b2-b191-6aeb039bd1cd.png)
![image](https://user-images.githubusercontent.com/90348406/151740488-84e22f4c-a63b-4840-b392-5dfc41068861.png)
Without any themes: ![image](https://user-images.githubusercontent.com/90348406/151743224-c3883815-071a-48a3-9cbe-eb8e35df7481.png)

Or still with the bottom border to separate:
![image](https://user-images.githubusercontent.com/90348406/151742576-dfdb0426-92f9-48e5-b8c8-1c699ef179cd.png)
![image](https://user-images.githubusercontent.com/90348406/151742596-04b918cc-ccc6-4a00-b12f-128e69e7e413.png)

**Comment by Arashiryuu** [comment]
This is a per-theme compatibility basis, if a theme doesn't wish to support it then you can always just drop a bit of custom css in the bottom of your theme file if you want, plugin is designed to fit Discord's default styling.

N.B. - `var(0, 0, 0, 0)` is an error in css, would be better if you'd just do `transparent` instead.
