### ISSUE TITLE
[Bug] Can't hide text or voice channels in the context menu

### ISSUE THREAD

**Issue by Banaando** [Arashiryuu/crap#168]
**Which plugin is this about?**
HideUtils

**Describe the Bug**
When I right-click a voice channel or text channel to hide it, there isn't a `Hide Channel` option, so I can't hide said channel.

**To Reproduce**
Right-click a text or voice channel and try to hide it.

**Expected Behavior**
A `Hide Channel` option shows up and I can hide the channel.

**Screenshots**
![image](https://user-images.githubusercontent.com/67934979/152079382-da52822d-d5b4-4318-a379-8b32a061bddb.png)
![image](https://user-images.githubusercontent.com/67934979/152079678-ad47c4da-4a59-48ac-93d0-38a79a68bae0.png)

**Discord Version**
Stable

**Additional Context**
Installed plugins: HideUtils v2.1.55, ZeresPluginLibrary v2.0.0
No installed themes

**Comment by ClickyOSU** [comment]
It also is happening with my mod too
