### ISSUE TITLE
[Bug] No hide button on HideUtils context menu

### ISSUE THREAD

**Issue by ikeman2003** [Arashiryuu/crap#170]
**Which plugin is this about?**
HideUtils 2.1.56

**Describe the Bug**
The hide function does not at all appear in the context menus

**To Reproduce**
Attempt to use the context menus to hide a user or channel.

**Expected Behavior**
Have the option to hide the user or channel visible

**Screenshots**
![image](https://user-images.githubusercontent.com/96934345/152586472-d962a23a-13eb-4efe-bd78-8498b228ab88.png)
![image](https://user-images.githubusercontent.com/96934345/152586494-1fe43871-1ec4-4d50-8a58-484e6811eaac.png)

**Discord Version**
Stable 113404

BD 1.5.0

**Additional Context**

**Comment by Anonymous327** [comment]
You gonna fix this? Don't think this plugin has ever worked for me.

**Comment by ChunkleChip** [comment]
22 days later, and I can confirm as well that **this plugin is not working**. 
![image](https://user-images.githubusercontent.com/16302135/170812340-606f24ec-1c0c-4087-9c13-c5f4f1ae86c4.png)

Stable 130153 (69b15bb)
BetterDiscord 1.5.3
Host 1.0.9004 Windows 10 64-Bit (10.0.19044)

**Comment by Glaived** [comment]
https://github.com/Arashiryuu/crap/commit/f492dfb96793e541599c55b2491fa34f07222a08

Fixed:
- Context menu items appear in their context menu again.
- Hide User option appears in the context menu again.
- Hide Channel option appears in the context menu again.

**Comment by Anonymous327** [comment]
Still not seeing Hide User or Hide Channel.

**Comment by Arashiryuu** [comment]
What client are you using? Should all be working on Stable.

**Comment by Anonymous327** [comment]
Stable 131860 (d9eb652)
BetterDiscord 1.5.3

**Comment by Anonymous327** [comment]
Nevermind. It seems to work now. I had to uninstall the old and reinstall the plugin.
