### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by SunRaysFalls** [Arashiryuu/crap#171]
**Which plugin is this about?**
Member Count

**Describe the Bug**
It doesn't save it's settings after reloading discord or starting it and on startup it keep showing the changelog/

**To Reproduce**
install plugin, reload discord or close it and start it again 

**Expected Behavior**
After settings have been set, it should retain them and after first changelog appearance, it should not appear again at each start 

**Discord Version**
Stable last version

**Comment by Arashiryuu** [comment]
sounds like you could have a corrupted config file, try deleting the `.config.js` file for the plugin

**Comment by SunRaysFalls** [comment]
> sounds like you could have a corrupted config file, try deleting the `.config.json` file for the plugin

Thank you, that was the issue. Will close this one now.
