### ISSUE TITLE
[Bug] HideUtils ContextMenu not showing up

### ISSUE THREAD

**Issue by Rollekk** [Arashiryuu/crap#172]
**Which plugin is this about?**
HideUtils v2.1.57

**Describe the Bug**
Hide User/Channel/Server not showing up in Context menu

**To Reproduce**
1. Right Click on any user in discord
2. Notice there is no "Hide user" option in context menu

**Expected Behavior**
Show "Hide user" on right click

**Screenshots**
![image](https://user-images.githubusercontent.com/48874046/157525701-4402f7cd-3be7-45cb-9e92-799f45da20e5.png)

**Discord Version**
Stable 117918 (4f4515d)
BetterDiscord 1.5.2

**Comment by Arashiryuu** [comment]
known issue see #170
