### ISSUE TITLE
HideUtils v2.1.57 no longer working.

### ISSUE THREAD

**Issue by ClickyOSU** [Arashiryuu/crap#173]
Hide Utils

The Plugin isn't working anymore, I cannot hide people, or channels anymore.

Right click and have the ability to hide channels/people.

![image](https://user-images.githubusercontent.com/42359579/158899045-1d05f864-c8e4-481c-bcd8-2d335c1d0571.png)
![image](https://user-images.githubusercontent.com/42359579/158899085-e815f813-facc-4d17-9507-9b4f93167b2e.png)

Discord Stable 119594, BetterDiscord 1.5.2

**Comment by Arashiryuu** [comment]
known issue, see #170
