### ISSUE TITLE
[HideServerChannels][Feature Request] Add hotkeys to hide/show panels

### ISSUE THREAD

**Issue by Liante-0216** [Arashiryuu/crap#18]
Hi, I found your plugin recently and was wondering if you would consider adding some keyboard shortcuts to hide/show channels and/or servers.
Specifically: I use it to hide the channels but I'm left with no way to know if someone wrote in a different channel of the same server. I'd love to have a way to see or check if there was activity in some other channel.

Thanks!

**Comment by Arashiryuu** [comment]
Do you mean just keybinds so you don't have to click the buttons in the header? Or were you thinking of something else?

**Comment by Liante-0216** [comment]
that's exactly what I was thinking, but any solution that lets me see that there's new messages in some other channel would suffice =)
