### ISSUE TITLE
[Feature] Don't count the bots as "member"

### ISSUE THREAD

**Issue by yami-no-tusbas** [Arashiryuu/crap#181]
**Which plugin is this about?**
MemberCountv2.2.17

**Is your feature request related to a problem? Please describe.**
No.

**Describe the feature you'd like**
A toggle to count or un-count the "bots", since they are not really "member" in a server.

**Additional context**
Some servers have dozens of them, so it impact the real member count times to times. (Making them seems bigger than they really are.)

**Comment by Arashiryuu** [comment]
duplicate of #160
