### ISSUE TITLE
[Bug] HideUtils cannot hide channels

### ISSUE THREAD

**Issue by Saltssaumure** [Arashiryuu/crap#182]
**Which plugin is this about?**
HideUtils

**Describe the Bug**
Selecting "Hide Channel" from the right-click menu does not actually hide the channel, though the "Channel has successfully been hidden" toast appears.

**To Reproduce**
1. Right-click any channel (voice or text)
2. Select "Hide Channel"

![Discord_iJM11s09Dw](https://user-images.githubusercontent.com/29710355/174910424-0cb79a14-2977-4338-995f-0063cec5b345.gif)

**Discord Version**
Stable 132979 (06cd218)
BetterDiscord 1.5.3
Host 1.0.9005 Windows 10 64-Bit (10.0.19042)

**Additional Context**
No other plugins in folder, except ZeresPluginLibrary.
Right-clicking to hide channel categories seems to work, though it only removes the category name.

**Comment by Arashiryuu** [comment]
Fixed, and having the option to hide a category name was unintentional, that should also be fixed now.
