### ISSUE TITLE
[Bug] MemberCount

### ISSUE THREAD

**Issue by JustSomeRandomGuy3** [Arashiryuu/crap#186]
**Which plugin is this about?**
MemberCount

**Describe the Bug**
It says "MemberCount Component Error" and leave a long space

**To Reproduce**
Turn on MemberCount (in my case, after reinstall with v1.5.3-hotfix2)

**Expected Behavior**
It should appear with something like this: 
![image](https://user-images.githubusercontent.com/102457568/182518274-5d060af3-d563-4b40-a294-d9b8950a847b.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/102457568/182517514-71fcefbd-023f-4fed-9f91-da90351bafb8.png)

**Discord Version**
Canary 139684 (95340d3)
BetterDiscord 1.5.3-Hotfix2
Windows 10

**Additional Context**
I'm not too sure if the error came from the library plugin tho

**Comment by Nimon77** [comment]
Same error here, seem that the variable `Dispatcher` is undefined

<img width="415" alt="image" src="https://user-images.githubusercontent.com/11821952/182580016-4a460994-9846-4bd4-a17e-d636b0e2018e.png">
<img width="458" alt="image" src="https://user-images.githubusercontent.com/11821952/182580058-93c51aaf-f166-413c-9fea-0bcbc2cd1f4f.png">

**Comment by Pokesketch** [comment]
Having the same issue here. Had to disable it temporarily.
