### ISSUE TITLE
[Bug] Hideutils hide option not display

### ISSUE THREAD

**Issue by Soulivan71** [Arashiryuu/crap#192]
**Which plugin is this about?**

Hideutils

**Describe the Bug**

I can't see the hide option on channels

**Discord Version**

PTB Ptb 149102 (e4eceb7)

![image](https://user-images.githubusercontent.com/36502190/192166729-efffcf3f-20df-48a6-b474-0f90e0c14019.png)
Im not having the hiding option on channels/servers 
![image](https://user-images.githubusercontent.com/36502190/192166767-e7c6b6e5-4561-4013-b8b3-b91f658d72b7.png)

Im having the option on folders/users

**Comment by Soulivan71** [comment]
Still not working with the new version

**Comment by Arashiryuu** [comment]
Discord has since made further breaking changes, this time it broke
basically everything though so it's unlikely there will be a fix going
forward

**Comment by Technetium1** [comment]
Or at least for an extended period... There is no official ETA on any fixes.

**Comment by Soulivan71** [comment]
An update ?
