### ISSUE TITLE
Turns off by itself or doesn't work at all.

### ISSUE THREAD

**Issue by Eggtooth** [Arashiryuu/crap#20]
Another issue after last fix. After last commit, the plugin doesn't work at all as intended. Switching to other channel causes plugin to either turn off completely or unhide hidden users. When it turns off by itself, it's impossible to turn it on as when you switch off options tab or go back to chat, it switches back off again. Doesn't have the right click functionality too.

Lastest Discord version and latest BandagedDiscord.

**Comment by Arashiryuu** [comment]
Yeah, Discord changed the internal structure of some data which caused the previous issues, and renamed a module the plugin uses causing the current one.

**Comment by Eggtooth** [comment]
Thank you so much for making this though. I wanted to message you somehow to thank you for that plugin, so I am tahnking here <3
