### ISSUE TITLE
[Bug] DateViewer plugin broken

### ISSUE THREAD

**Issue by moosje2003** [Arashiryuu/crap#202]
**Which plugin is this about?**
DateViewer

**Describe the Bug**
can't open pugin settings

**To Reproduce**
open plugin settings

**Expected Behavior**
editing the settings

**Screenshots**

**Discord Version**
stable 
![image](https://user-images.githubusercontent.com/61630365/219075474-220664e9-0e90-41e2-8442-50644e66d00e.png)

**Comment by Lrive** [comment]
i'm having this issue now.
