### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by PAULXD1359** [Arashiryuu/crap#212]
Al the seccion of the date and hour is turned

**To Reproduce**
1) Enable the plugin lol

**Expected Behavior**
Show date and time on a human-readable way

**Screenshots**
![image](https://github.com/Arashiryuu/crap/assets/103274925/ba2b4b95-61c0-434d-a823-95a3d0729515)

**Discord Version**
Stable 233846 (546f66e) Host 1.0.9018 x86 (37723) Windows 10 64-Bit (10.0.19045)

**Comment by Arashiryuu** [comment]
nice meme
