### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by berkkrkc09** [Arashiryuu/crap#213]
**Which plugin is this about?**

The information is backward.
**Describe the Bug**

Every information this plugin writes on the screen is written backward.
**To Reproduce**

I just launched Discord with all my plugins enabled.
**Expected Behavior**

All information should be written normally.
**Screenshots**

https://imgur.com/a/uccNxep
**Discord Version**

Stable 235819 (7319f9a)
**Additional Context**

I have changed the background color but didn't touch anything else. It's the same with a fresh plugin install. I didn't have this issue 2(?) weeks ago. BetterDiscord core v1.9.3, DateViewer v1.0.6.
My plugin list:https://gist.github.com/berkkrkc09/d2e0f6fd21d85ea829c89bb3f25abbe8

**Comment by Arashiryuu** [comment]
# 🤔
If you move all your plugins out of your plugin folder and only run this one, does it still happen?

**Comment by berkkrkc09** [comment]
I have been testing with plugins and it seems like CollapsableUI by programmer2514 is causing this. I will report this to them now. I don't know why I didn't test with no plugins. Sorry for taking you time.

**Comment by berkkrkc09** [comment]
Here is their issue page: https://github.com/programmer2514/BetterDiscord-CollapsibleUI/issues/92
just in case you are curious and they already found the cause of this.

**Comment by berkkrkc09** [comment]
Hey, they forked DateViewer situation as a seperate issue from the link I sent before and there, they are saying that it's a compatibility issue. Maybe it was an issue on both plugins? IDK.
here is the forked issue:https://github.com/programmer2514/BetterDiscord-CollapsibleUI/issues/95
