### ISSUE TITLE
[Bug] HideUtils plugin is broken v2.1.58

### ISSUE THREAD

**Issue by MohammadAliKid** [Arashiryuu/crap#214]
**Which plugin is this about?**
General hiding options for servers/users and such

**Describe the Bug**
Context menu not appearing and when going to plugin settings for it, and clicking one of the options for users/servers/channels etc. it crashes discord

**To Reproduce**
Opening and clicking one of the settings options in the plugin settings menu

**Expected Behavior**
Having the ability to hide certain things and the settings menu not crashing discord

**Screenshots**
Error that appears when it crashes
![image](https://github.com/Arashiryuu/crap/assets/26622938/e2f0bd52-ca65-4391-a7bc-3128bc6d70b6)

**Discord Version**
Betterdiscord v1.9.5 latest
Stable 242566 (12901f7) Host 1.0.9022 x86 (39098) Windows 10 64-Bit (10.0.19045)

**Comment by Arashiryuu** [comment]
Known, see #195

**Comment by phoenixResearch** [comment]
Hello, upon attempting to open the settings, it crashes discord, also, there is no context menu option to hide
