### ISSUE TITLE
ChatUserIDsRedux [Bug] 

### ISSUE THREAD

**Issue by BR0674** [Arashiryuu/crap#217]
**Which plugin is this about?**
ChatUserIDsRedux.plugin.js

**Describe the Bug**
User ID is not showing up next to their name even though the plugin is enabled.

**To Reproduce**
Enable the plugin and reload Discord.

**Expected Behavior**
User ID to appear next to user's name in chat.

**Screenshots**
Currently looks like this (with or without theme enabled): https://imgur.com/a/5nG8ze7

**Discord Version**
Stable 252966 (b583bea)
Host 1.0.9026 x86 (40844)
Windows 10 64-Bit (10.0.22631)

**Additional Context**
N/A.

**Comment by Arashiryuu** [comment]
Known as of #196.
