### ISSUE TITLE
[Bug] MemberCount - behaves strangely within threads

### ISSUE THREAD

**Issue by ColonelGerdauf** [Arashiryuu/crap#218]
**Which plugin is this about?**
MemberCount

**Describe the Bug**
numbers are written in as a singular line header when in a thread, whereas in a channel it works as intended. (minus odd quirks with Collapsible UI).

**To Reproduce**
install BDFDB, then MemberCount, then install the theme ClearVision to make this problem visible.
After a bit of theme customization, hop onto a thread to see threads behaving strangely in relation to channels.

**Expected Behavior**
For the box to be applied equally between the threads as it does with channels when other plugins do not interfere with its functionality.

**Screenshots**
![image](https://github.com/Arashiryuu/crap/assets/6895655/ee5bcccc-e58b-4cf9-8891-4e967d306d0b)

**Discord Version**
Stable

**Comment by Arashiryuu** [comment]
Themeing issues are not typically something you report here.
