### ISSUE TITLE
[Bug] member count is flipped

### ISSUE THREAD

**Issue by rocketbuuny** [Arashiryuu/crap#219]
MemberCount plugin

The bug is that whenever I use the plugin, the words and numbers are flipped.

![image](https://github.com/Arashiryuu/crap/assets/140739502/350f02ec-091e-4c08-9e0c-66f00fc85fdf)

Discord ver:
Stable 256231 (96a39c5)

**Comment by Arashiryuu** [comment]
Are you using CollapsibleUI?

**Comment by ColonelGerdauf** [comment]
I can confirm that CollapsibleUI is likely responsible, and specifically the `resizable member list` option

**Comment by Arashiryuu** [comment]
Similar thing happend with DateViewer a while back so I suspected that this might be the cause.

**Comment by rocketbuuny** [comment]
I am using collapsible UI! Thank you for letting me know of this plugin conflict.
