### ISSUE TITLE
[Bug] MemberCount

### ISSUE THREAD

**Issue by TinKode** [Arashiryuu/crap#222]
**Which plugin is this about?**
MemberCount

**Describe the Bug**
It is displaying the count as if its mirrored somehow

**To Reproduce**

**Expected Behavior**

**Screenshots**

![uga](https://github.com/Arashiryuu/crap/assets/11066480/8463f698-763a-45bb-b87d-4045fdffa1b3)

**Discord Version**
Stable

**Additional Context**

**Comment by Arashiryuu** [comment]
CollapsibleUI is causing this.
