### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by foursplaysroblox** [Arashiryuu/crap#224]
**Which plugin is this about?**

DateViewer plugin
**Describe the Bug**

Won't show in the member list (sometimes) and color does not match with theme
**To Reproduce**

just go to any channel that shows a member list
**Expected Behavior**

Should show the date and time and match with the theme
**Screenshots**

![image](https://github.com/Arashiryuu/crap/assets/82078139/f3ccdf45-224f-4dd6-b954-5a3d2c2854d1)
i forgot the screenshot that wont show it
**Discord Version**

PTB
**Additional Context**

**Comment by Arashiryuu** [comment]
I don't develop on/for any of the test builds (PTB/Canary), and colours not matching your theme is a theme issue - the plugin is designed to use the same css variables that Discord uses for their memberlist, and mimics the other headers in the list.
