### ISSUE TITLE
[Bug] MemberCount plugin displays backwards

### ISSUE THREAD

**Issue by NootRecruit** [Arashiryuu/crap#226]
**Which plugin is this about?**
MemberCount

**Describe the Bug**
The member- and onlinecount are completely flipped, all letters being oriented to the wrong side (see screenshot)

**To Reproduce**
I have yet to find out what causes the issue

**Expected Behavior**
Regular orientation

**Screenshots**
![grafik](https://github.com/Arashiryuu/crap/assets/169262602/7919a065-5100-4bc0-97b3-34bb6d2df717)

**Discord Version**
Stable 290998 

**Additional Context**
Problem was after a clean install of discord and betterdiscord with no prior installation of either on this device

**Comment by Arashiryuu** [comment]
This is a known conflict with the CollapsibleUI plugin.

**Comment by NootRecruit** [comment]
Damn I wasn't aware, thanks for the heads up!
