### ISSUE TITLE
Member Count is not Working

### ISSUE THREAD

**Issue by deadmau1** [Arashiryuu/crap#227]
![image](https://github.com/Arashiryuu/crap/assets/115784191/6131a763-228f-42cf-90f5-930928422967)

**Comment by EclipsesDev** [comment]
yeah

**Comment by EclipsesDev** [comment]
@Arashiryuu when will u update the one on betterdiscord web

**Comment by Arashiryuu** [comment]
> @Arashiryuu when will u update the one on betterdiscord web

@EclipsesDev
The BetterDiscord website updates its versions after going through the review process so there's nothing I can do regarding that

**Comment by EclipsesDev** [comment]
> > @Arashiryuu when will u update the one on betterdiscord web
> 
> @EclipsesDev The BetterDiscord website updates its versions after going through the review process so there's nothing I can do regarding that

well thats a bit weird, it shouldn't take this long.. ohh and also when will u fix hideutils?
