### ISSUE TITLE
Greentext in compact doesn't stop at line breaks

### ISSUE THREAD

**Issue by FichteFoll** [Arashiryuu/crap#24]
![2018-12-10_13-14-36](https://user-images.githubusercontent.com/931051/49732045-8fe41080-fc7d-11e8-895d-7f8a72b9fa2d.png)

![2018-12-10_13-15-33](https://user-images.githubusercontent.com/931051/49732082-b3a75680-fc7d-11e8-9534-ed6211c58548.png)

Probably caused by the recent bugfix for compact since this used to work.

**Comment by FichteFoll** [comment]
Now it seems like an additional newline is added when there was a single empty line between greentext and normal text.

![2018-12-11_00-28-15](https://user-images.githubusercontent.com/931051/49768216-ee3fdc00-fcdb-11e8-92e9-04b160eafb27.png)

![2018-12-11_00-30-22](https://user-images.githubusercontent.com/931051/49768232-f9930780-fcdb-11e8-9d5b-1fb7fa31b907.png)

**Comment by Arashiryuu** [comment]
Updated it again.

Boy do I hate compact mode...

**Comment by FichteFoll** [comment]
But it's the best mode … :cry: 

Now everything's is well.
