### ISSUE TITLE
HideUtils v1.1.16 - Members List bug after hiding users

### ISSUE THREAD

**Issue by M-archand** [Arashiryuu/crap#26]
Hello, after hiding users the Members List bugs out and does not show a full pane of users unless you scroll down. This occurs no matter the height of the discord client. I've attached some example pictures below to better explain. As you can see in the 1st image, there is a gap where users don't show at the bottom. The 2nd image is from scrolling ever so slightly, there is no minimum threshold before it fixes.

![untitled](https://user-images.githubusercontent.com/13469995/51076157-54b57280-166b-11e9-997b-6c1d2f3b75ab.png)
![untitled1](https://user-images.githubusercontent.com/13469995/51076229-26846280-166c-11e9-8bac-8c1ca3221e2b.png)

**Comment by Arashiryuu** [comment]
Couldn't reproduce your issue, are you sure it isn't your theme?

**Comment by M-archand** [comment]
Issue still persists when disabling theme. Issue disappears when disabling the hideutils plugin.

**Comment by M-archand** [comment]
I've just noticed something else which could be why you can't reproduce. This users I'm hiding are bots (you'll see that there are only 3 showing when the group list says 7). They're always online. When I make the Discord window short enough that the section with the hidden profiles ("BOTS") is below the part of the Members List that fits on the screen without scrolling, the issue does not occur and the Members List goes all the way to the bottom without leaving a gap.
![sgotwlx](https://user-images.githubusercontent.com/13469995/51078034-89cebe80-1685-11e9-9e5d-e89d5ece809d.png)

**Comment by just-Addict** [comment]
I've been thinking, all of the users I've been hiding are in a group that is almost at the top of the memberlist with only on average 5-8 other users above that in owner//bot/mod/support groups.
My inention was to hide all users in that group, but the more users I hid, the bigger the gap became to the point that now I have this large gap that doesn't even go away when scrolling down and only occasionally a few of the still unhidden groupmembers flicker into visibility and dissapear from view on the slights mousewheel movement,

It's like Discord simply doesn't load in anymore users almost as if it knows there are enough loaded to fill the memberlist to the bottom of the panel.

**Comment by Arashiryuu** [comment]
That is pretty much it, Discord lazy-loads the member list.
