### ISSUE TITLE
MemberCount broke yet again.

### ISSUE THREAD

**Issue by tryoutuser** [Arashiryuu/crap#28]
After trolling its users for releasing v0.0.302, then pushing out v0.0.303 after few hours. Goddamn the discord team can't make up their minds lmao.

**Comment by tryoutuser** [comment]
Seriously joking aside, the plugin did started but the counter didn't appear in users list.

![image](https://user-images.githubusercontent.com/35561383/51264254-ac940680-19e8-11e9-80ac-f2a81c5c857a.png)

![image](https://user-images.githubusercontent.com/35561383/51264272-b7e73200-19e8-11e9-8d20-2247a9792031.png)

**Comment by Arashiryuu** [comment]
Any errors in console? It's working fine for me and my version is the same as the updated one on my repo.
