### ISSUE TITLE
HideUtils No longer works

### ISSUE THREAD

**Issue by Eggtooth** [Arashiryuu/crap#29]
So after latest update of discord, HideUtils fail to start. In fact I think all of the plugins are broken.

http://prntscr.com/m818n9

**Comment by just-Addict** [comment]
Same for the other plugins requiring Zerebos's PluginLibrary.  (e.g. KillXD, MemberCount, etc)
Seems to be because of the use of a deprecated version.

**Comment by Eggtooth** [comment]
Will this get updated somehow? If so, will I need to download anything?
