### ISSUE TITLE
 HideUtils v1.1.17 not working

### ISSUE THREAD

**Issue by StylinGreymon** [Arashiryuu/crap#32]
the hide options aren't visible in context menu, and when manually adding server ID to hide list, console throws this error:
```javascript
Uncaught TypeError: Cannot read property 'getGuild' of undefined
at HideUtils.servPush (/home/greymon/.config/BetterDiscord/plugins/HideUtils.plugin.js:656)
```

**Comment by Arashiryuu** [comment]
Going to push an update, tell me if the issue persists after you get the update.

**Comment by StylinGreymon** [comment]
able to hide everything again.
however, the context menu doesn't disappear after hiding servers or channels.
that's more of a nitpick, though.

thanks for the fix.
