### ISSUE TITLE
[MemberCount] Still getting the following error in the console in Release/PTB/Canary

### ISSUE THREAD

**Issue by just-Addict** [Arashiryuu/crap#33]
still getting the following error in the console in Release/PTB/Canary
And yes, Zerebos' Plugin library is installed and activated.

According to Zerebos, this error is caused by referencing a deprecated/discontinued version of the library
![2019-01-20_162152](https://user-images.githubusercontent.com/19715616/51441935-56b8aa80-1cd7-11e9-9691-c5b004e58aa0.png)

_Originally posted by @just-Addict in https://github.com/Arashiryuu/crap/issues/27#issuecomment-455879781_

**Comment by Arashiryuu** [comment]
I'd rather you just comment on a previous conversation about the issue, as opposed to opening what is essentially just a duplicate issue.
