### ISSUE TITLE
MemberCount shows broken character

### ISSUE THREAD

**Issue by Mr-Mcshinyorb** [Arashiryuu/crap#37]
Version 2.07 shows a replacement character instead of a hyphen. I disabled my other and themes, and the issue still occurred.

![image](https://user-images.githubusercontent.com/42078663/53046748-adf19c80-3488-11e9-9cac-c9bc4a22a750.png)

The element looks like this:
`<div class="membersGroup-v9BXpm da-membersGroup" id="MemberCount">Members�38977</div>`
<div class="membersGroup-v9BXpm da-membersGroup" id="MemberCount">Members�38977</div>

BTW loving the plugin!

**Comment by Arashiryuu** [comment]
Is it consistent?

**Comment by Mr-Mcshinyorb** [comment]
It seems to be consistent on my end, am I the only one with the issue?

**Comment by Arashiryuu** [comment]
Currently you're the only one to report this, so as far as I know, yes.

**Comment by Mr-Mcshinyorb** [comment]
The problem appears to have fixed itself after a reinstallation of Discord, so it was just me.
