### ISSUE TITLE
HideServersChannelsRedux Crashing Discord

### ISSUE THREAD

**Issue by ejox** [Arashiryuu/crap#39]
The plugin worked fine until 19th of April, but just now I noticed how Discord started crashing whenever I tried to switch to PMs or servers. Pretty much any action does this. At first I didn't know what was causing it, but I basically turned every plugin on one at a time and immediately switched between PMs to check if this was the issue.

When I enabled your plugin and tried switching PMs, instant crash. I also noticed how the hide channels and servers buttons on the top right were transparent, but I could still click on them. When I did, also instant crash.

I'm not much of a coder so I dunno why it's happening, but I know Discord had an update just now because it was working fine before I updated.

I felt like letting you know, but the BD Discord is unavailable for me so I had to message you here. This plugin is one of my favorite ones so I hope you succeed in fixing this!

**Comment by Arashiryuu** [comment]
I've recently pushed an update that resolves this issue, please update as soon as you can.
