### ISSUE TITLE
after recent update, servers aren't hidden, and I can no longer hide users

### ISSUE THREAD

**Issue by StylinGreymon** [Arashiryuu/crap#42]
when attempting to hide a server, I get this error in console:

` d2b826a….js:45 GET https://cdn.discordapp.com/icons/396144014128054275/7d2cd3d….webp? 404
d2b826a….js:49 GET https://discordapp.com/api/v6/invite/nvS99E?with_counts=true 404
`﻿

**Comment by Arashiryuu** [comment]
What build of Discord are you using?

**Comment by StylinGreymon** [comment]
0.0.9-3
Stable branch, on Manjaro Linux.

**Comment by Arashiryuu** [comment]
Is it consistent?

**Comment by StylinGreymon** [comment]
I'm not sure what you mean by consistent, but when I attempt to hide a server, a little tooltip comes up saying that it's been successfully hidden, even thought it's still visible.
Trying to hide it again produces a tooltip that says server is already hidden.

Strangely, I can hide channels just fine.

**Comment by Arashiryuu** [comment]
Sometimes on startup I get a bug where it'll double/triple load plugins and that usually causes other plugins to fail so I was asking to see if it might have been that, but that doesn't seem to be it. There's no reason for yours to be acting like that from what little information I have.

I can't reproduce it on my end also.

**Comment by StylinGreymon** [comment]
after updating there were a few weird bugs, like 2 Hide Server options in the context menu, so I just deleted the plugin and redownloaded it, and everything is back in working order. Should have probably tried that first, sorry.

Thanks for the help!

**Comment by Arashiryuu** [comment]
That's what I meant about the startup bug, just reloading the window should fix it normally. Though I have no idea why it even happens.
