### ISSUE TITLE
Greentext doesn't include spans

### ISSUE THREAD

**Issue by FichteFoll** [Arashiryuu/crap#44]
The greentext plugin doesn't extend over inline spans like `<em>`, `<strong>`, `<s>` or `<code>`, which results in line breaks being inserted.

![2019-05-19_20-46-38](https://user-images.githubusercontent.com/931051/57986630-a5086b00-7a77-11e9-90d6-edfbc096ede1.png)
![2019-05-19_20-46-43](https://user-images.githubusercontent.com/931051/57986631-a6399800-7a77-11e9-8d62-e3a619b53e79.png)
![2019-05-19_20-49-35](https://user-images.githubusercontent.com/931051/57986634-a6d22e80-7a77-11e9-8663-2bcd0d26d01e.png)

Source for the last example:

![2019-05-19_20-50-06](https://user-images.githubusercontent.com/931051/57986639-be111c00-7a77-11e9-9f56-8e85d9341067.png)

**Comment by Arashiryuu** [comment]
Interesting, that only seems to happen in compact mode.

**Comment by FichteFoll** [comment]
I can imagine you'd run into the same issue on cozy otherwise and would have fixed it long ago. It's been an issue for months, I believe, but I never bothered reporting.

**Comment by FichteFoll** [comment]
Also applies to links, btw.
