### ISSUE TITLE
[HashTagsReborn] Exclude guild channels

### ISSUE THREAD

**Issue by KaKi87** [Arashiryuu/crap#46]
Hey,

Please exclude existing channels in guild to be converted to hashtags, which make them non-clickable.

Thanks

**Comment by KaKi87** [comment]
![2019-09-25 22_45_40-Discord](https://user-images.githubusercontent.com/21284089/65638447-6ca90880-dfe6-11e9-8656-a29efd41e96c.png)

**Comment by dutchwizard2** [comment]
haveing same issue as the SS marked above

https://user-images.githubusercontent.com/21284089/65638447-6ca90880-dfe6-11e9-8656-a29efd41e96c.png
