### ISSUE TITLE
[Bug] When I click hide channel in some servers it does not work.

### ISSUE THREAD

**Issue by Kederan** [Arashiryuu/crap#49]
**HideUtils**

**When I click hide channel it doesn't work for some servers. But works for others.**

**I use the plugin like I have normal used it before and it has given me the bug.**

**When I click hide channel I was expecting for the channel to be hidden from me.**

**Screenshots**

![2019-08-21_17-36-19](https://user-images.githubusercontent.com/19885815/63470383-8b8e0b00-c43a-11e9-9a71-9dbfb0f8c315.gif)

**Stable Discord**

**I tried trouble shooting the issue before I submitted this bug. I turned off and on the plugin. Refreshed the client multiple times and I still get the bug.**

**Comment by Arashiryuu** [comment]
What version number of HideUtils are you on?

**Comment by Kederan** [comment]
> What version number of HideUtils are you on?

v2.1.7

**Comment by Arashiryuu** [comment]
Okay, can you go to your plugin folder and remove any `.plugin.js` file(s) titled `HideUtils`, then download a fresh copy, then restart your Discord client and see if the issue persists?

The last time I saw this I was getting it because I had 2 versions of the plugin running at the same time, and it bugged out.

**Comment by Infinidoge** [comment]
Can repro on my end, removed HideUtils (and config) and reinstalled, no change in behavior.

**Comment by Arashiryuu** [comment]
Any errors in console related to the plugin?

**Comment by Infinidoge** [comment]
None that I can find.

**Comment by Arashiryuu** [comment]
I'm out of ideas, and I can't reproduce it on my end either.

**Comment by Kederan** [comment]
> Okay, can you go to your plugin folder and remove any `.plugin.js` file(s) titled or containing `HideUtils`, then download a fresh copy, then restart your Discord client and see if the issue persists?
> 
> The last time I saw this I was getting it because I had 2 versions of the plugin running at the same time, and it bugged out.

I just did that and I still get the error. 

It may have something to do with the number of people online. 

This is the server it happens in and other big servers. https://discord.gg/scrims

**Comment by Arashiryuu** [comment]
It's not due to a high volume of users or channels.

Like I said I've only ever had it when something's been faulty like two files for the same plugin running together, but the only other possibility I can fathom is a faulty Discord start up. Which usually fixes itself upon a reload or two.

**Comment by Kederan** [comment]
okay well I'll just use the "hide mute" channels until there is a fix. 

I appreciate you adding the "purge hidden channels" & "Unhide channel" feature.

Do you have a discord server for your utilities?

**Comment by Arashiryuu** [comment]
I do not have a Discord server for my plugins, no.

**Comment by Arashiryuu** [comment]
Issue went stale and doesn't appear to be a problem anymore.
