### ISSUE TITLE
[Bug] HideUtils Crash on Newest Update

### ISSUE THREAD

**Issue by SupahMario** [Arashiryuu/crap#52]
**Which plugin is this about?**
HideUtils

**Describe the Bug**
With the newest update, Discord instantly crashes whenever entering a text channel.

**To Reproduce**
1. Enable Plugin
2. Open Server
3. Enter a Text Channel _(happens automatically)_

**Expected Behavior**
Messages load, all appears as normal, and blocked items do not appear.

**Discord Version**
Stable, "New Light Theme"

**Comment by Infinidoge** [comment]
Can reproduce on canary, latest update.

**Comment by TheDarkBomber** [comment]
Can reproduce on PTB, latest update. Well, "can reproduce" is an understatement since, finding out that this plugin was the issue was a monotonous task.

**Comment by TheDarkBomber** [comment]
@Arashiryuu
