### ISSUE TITLE
[Bug] Greentext doesn't load in newest version

### ISSUE THREAD

**Issue by FichteFoll** [Arashiryuu/crap#54]
**Which plugin is this about?**

**Describe the Bug**

```
greenText.plugin.js | Could not be constructed. | Cannot read property 'trim' of undefined
```

**To Reproduce**
Just put the file into your plugins.

**Discord Version**
Stable, just updated.

`[NATIVE INFO] host 0.0.9, modules: discord_desktop_core: 3, discord_erlpack: 1, discord_spellcheck: 1, discord_utils: 1, discord_voice: 3, discord_game_utils: 1, discord_rpc: 2, discord_zstd: 1`

**Comment by SakiSakiSakiSakiSaki** [comment]
I also have the same problem.
