### ISSUE TITLE
[Bug] [MemberCount] [AfterPatch]

### ISSUE THREAD

**Issue by MrZeroLord** [Arashiryuu/crap#56]
![OFTTsvqjVs](https://user-images.githubusercontent.com/40106969/64744844-bfbe8e00-d505-11e9-87e2-7ec16329da65.gif)
still kinda overlapping 
Theme:
https://github.com/mwittrien/BetterDiscordAddons/tree/master/Themes/BasicBackground

**Comment by MrZeroLord** [comment]
but thanks for the quick reaction to the bug ^^

**Comment by holysnipz** [comment]
"Tell DevilBro to support this plugin" is the real solution for this "bug"
