### ISSUE TITLE
[Bug] HideUtils Unable to hide channels in servers

### ISSUE THREAD

**Issue by Kederan** [Arashiryuu/crap#59]
**Which plugin is this about?**
HideUtils

**Describe the Bug**
In servers with a lot of channels you are unable to hide channels at the bottom of the server. You are unable to right click any of the channels to hide them. Such as [Enigma](https://discord.gg/ZfYUced)

**To Reproduce**
Certain channels you can hide by right clicking and then selecting "Hide Channel". But on other channels you are not able to right click the channel at all.

**Expected Behavior**
Right click a channel within the server then select "Hide Channel" to hide a channel in the discord server.

**Screenshots**
![2019-10-08_16-24-26](https://user-images.githubusercontent.com/19885815/66430839-de228700-e9e8-11e9-944a-3c82ad436815.gif)

**Discord Version**
Stable

**Comment by Arashiryuu** [comment]
This is an issue that comes from having some categories collapsed and some open, and is a flaw of Discord's.

**Comment by Kederan** [comment]
I tested again with the categories not collapsed and I still get the same bug
![2019-10-08_22-37-22](https://user-images.githubusercontent.com/19885815/66447487-72f2a800-ea1c-11e9-96e6-ba7f1b07be6a.gif)

**Comment by Kederan** [comment]
The issue was when I had the plugin accountswitcher by l0cc4lh057 on while hiding the channels
