### ISSUE TITLE
[Bug] ChatUserIDsRedux does not show any settings

### ISSUE THREAD

**Issue by dudeamax99** [Arashiryuu/crap#69]
**Which plugin is this about?**
ChatUserIDsRedux

**Describe the Bug**
When clicking settings in Discord and then clicking the drop down, no settings are shown.

**To Reproduce**
Attempt to change settings 

**Expected Behavior**
Able to change settings

**Screenshots**
[No settings shown](https://i.imgur.com/bGcEDfs.png)

**Discord Version**
Stable

**Comment by Arashiryuu** [comment]
[Known issue.](https://github.com/rauenzi/BDPluginLibrary/issues/10)

**Comment by Arashiryuu** [comment]
Forgot to close this, there is a standard html colorpicker setting as a holdover until the previous style react colorpicker setting comes back.
