### ISSUE TITLE
[Bug] MemberCount did not work on april fool

### ISSUE THREAD

**Issue by tryoutuser** [Arashiryuu/crap#73]
**Which plugin is this about?**
Membercount

**Describe the Bug**
No longer showing how many people in the members list for me today. This time I'm not doing mistake with "Exclude Server" button.
No matter what betterdiscord theme or default theme I use it's not showing.

**To Reproduce**
Take a look inside a server

**Expected Behavior**
It should show the counter as usual

**Screenshots**
![image](https://user-images.githubusercontent.com/35561383/78147203-6300d180-745d-11ea-864c-b20c0ace5df0.png)

**Discord Version**
Stable v0.0.306 with Bandaged BD

**Additional Context**
If I turn off the plugin and back on, sometimes the exclude server button in right click menu over a server icon appear as duplicate when using betterdiscord theme. Restarting discord fix this away, but when I do it again, it appeared.

**Comment by Glaived** [comment]
@Arashiryuu Do you have any information on the closing issue ? I have the exact same problem.

**Comment by Glaived** [comment]
#74
