### ISSUE TITLE
[Bug] MemberCount broke in Stable 62531 (624ac8f) Discord

### ISSUE THREAD

**Issue by minhngoc25a** [Arashiryuu/crap#81]
![image](https://user-images.githubusercontent.com/33834488/86137088-1178e900-bb17-11ea-81d5-2bfd7fbd700c.png)

MemberCount plugin is officially broke after I updated Discord. Even toggling it on/off won't do anything.

**Comment by Shady2kOver** [comment]
yup

**Comment by asportnoy** [comment]
+1

**Comment by Darkissou** [comment]
+1

**Comment by tryoutuser** [comment]
Can confirm. happened to me too
