### ISSUE TITLE
[Bug] HideUtils not hiding channels

### ISSUE THREAD

**Issue by ramenchef** [Arashiryuu/crap#82]
**Which plugin is this about?**
HideUtils

**Describe the Bug**
Hidden Channels are not hidden.

**To Reproduce**
None

**Expected Behavior**
Hidden Channels do not appear

**Screenshots**

**Discord Version**
Stable

**Additional Context**
Seems like a recent Discord update has broken this functionality.

**Comment by ItMeSarah** [comment]
Same for hidden users, they still appear on the list.
