### ISSUE TITLE
[Bug] Context Menu not highlighting "Hide Server" and other HideUtil options

### ISSUE THREAD

**Issue by iFailatGitHub** [Arashiryuu/crap#86]
**Which plugin is this about?**
HideUtils

**Describe the Bug**
Whenever I bring up the context menu for a server/user/channel for Discord, and I hover on "Hide Server/User/Channel", it doesn't get highlighted and it highlights the last option i picked instead.

**To Reproduce**
1. Right-click server, channel, or a user to bring up the context menu
2. Hover on Hide Server/Hide Channel/Hide User

**Expected Behavior**
Hide Server/Hide Channel/Hide User should be highlighted when hovered in the context menu

**Screenshots**
![DiscordPTB_U2Avn9p5wI](https://user-images.githubusercontent.com/56383324/87843510-b4877c00-c8e7-11ea-85ba-b951ebb6886e.png)

**Discord Version**
Discord Public Text Beta (DiscordPTB)

**Additional Context**
Any options from HideUtils don't get highlighted, I tried other plugins in the context menu and they're highlighted as expected when hovered on.

**Comment by MrZeroLord** [comment]
I can reproduce and confirm on Stable BBD 0.3.5
https://cdn.discordapp.com/attachments/543620396369444905/757723876062134292/vdcbcRUS2K.gif
