### ISSUE TITLE
[Bug] Can't see the member count on the server I run

### ISSUE THREAD

**Issue by Ownsin** [Arashiryuu/crap#87]
**Which plugin is this about?**
MemberCount

**Describe the Bug**
It works on every other server, but my server. For some reason, the member count won't show up for the server that I run and own but will show up for other servers. Oddly, it used to work just fine in the previous update, but you updated it 10 days and it stopped working ever since then.

**To Reproduce**
 No idea, It was working fine in the previous update, but you updated the plugin and now I can't see the member count on my server

**Expected Behavior**
For me to see the member count on my server. 

**Screenshots**
 N/A 

**Discord Version**
Stable

**Comment by Arashiryuu** [comment]
So remove your server from the blacklist? Right click the guild icon and click the button.

The update made it so that the plugin properly used its settings again, and by design it only ignores servers that are in its blacklist.

**Comment by Ownsin** [comment]
Oh, that fixed it. Thank you!

Sorry for the trouble. I didn't know about the blacklist feature.
