### ISSUE TITLE
[Bug] MemberCount: Element is not showing

### ISSUE THREAD

**Issue by Vandesm14** [Arashiryuu/crap#89]
**Which plugin is this about?**
Member Count

**Describe the Bug**
Member count element does not show

**To Reproduce**
None

**Expected Behavior**
Member count element does not show

**Screenshots**
![image](https://user-images.githubusercontent.com/23623276/89140508-d00d9c00-d50f-11ea-9ce8-dbeae2ae8c54.png)

**Discord Version**
Stable

**Additional Context**
None

**Comment by Arashiryuu** [comment]
If the issue persists can you check the console for possible errors related to the plugin and share them here.

**Comment by Arashiryuu** [comment]
Fixed in latest update.
