### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by minhngoc25a** [Arashiryuu/crap#92]
**Which plugin is this about?**
 
MemberCount

**Describe the feature you'd like**

The plugin also shows the number of current online members, like in "Accept invite" pop-up.

**Additional context**

![image](https://user-images.githubusercontent.com/33834488/93587560-4be67980-f9d4-11ea-8dae-72fd60456488.png)

**Comment by Arashiryuu** [comment]
Discord already does this natively, and there is no way to discern between "invisible" users and truly offline users, so it wouldn't really be doable.
