### ISSUE TITLE
HideUtils crashes Discord in latest version [Bug] 

### ISSUE THREAD

**Issue by KittyNinetales** [Arashiryuu/crap#97]
**Describe the Bug**
Discord crashes upon loading up the latest version of HideUtils v2.1.38 luckily I have Crash Recovery to recover from said crash, but I'm not sure what the problem is with said plugin, however, I hope it gets fixed soon :D

**Discord Version**
Stable

**Comment by Arashiryuu** [comment]
can you reproduce it?

**Comment by KittyNinetales** [comment]
It's not something that's reproducible, actually... It just crashes upon
loading up

**Comment by Arashiryuu** [comment]
Well then I guess you're just SOL unfortunately.

**Comment by Glaived** [comment]
I confirm the present of a crash at the launch of hideUtils, permanently

Discord: Stable
HideUtils: 2.1.38

**Comment by alnviana** [comment]
For me too, it started now. If I start discord without this plugin, download and load it, it crashes immediately.

Discord: Stable
HideUtils: 2.1.38

**Comment by minervamaga** [comment]
Same thing right here, did a systematic test this morning to determine what the source was and it's only this plugin.  Reproducible on every boot/ctrl-R with the plugin installed.

Discord version: https://cdn.discordapp.com/attachments/574799106124546069/777944817095016497/unknown.png
HideUtils: also 2.1.38

**Comment by williamjcm** [comment]
Here's the error in the console when HideUtils starts:

![image](https://user-images.githubusercontent.com/13572456/99296468-1da3df80-2847-11eb-88e5-1009ff2f3035.png)
