### ISSUE TITLE
Latest Version of HideUtils (AGAIN) [Bug] 

### ISSUE THREAD

**Issue by KittyNinetales** [Arashiryuu/crap#98]
**Which plugin is this about?**
HideUtils (again) gives an error which I checked through console this time

**Plugin version**

2.1.39

**Describe the Bug**
The errors say it might not be playing nice with other plugins, which to say, I don't know but it could be a possibility

**To Reproduce**
Turn on HideUtils, CrashRecovery turns it off, says it's HideUtils' fault (again)

**Screenshots**
![image](https://user-images.githubusercontent.com/16514642/100043339-138f5d00-2dc2-11eb-983d-4cc8eff2d191.png)

**Discord Version**
Canary

**Additional Context**
I love your plugin, mate. But, recently it's been not working at all, and idk why it doesn't like to play nice with CrashRecovery or it may be some other plugin, I don't know, but seems to me maybe I might have to disable it for a good while

**Comment by 4g0tt3nSou1** [comment]
Can Repo; 
Stable 72376 (75e36d9)
BBD 0.3.5
Host 0.0.12
Injector 0.6.2
Linux 64-Bit (5.4.0-53-Generic) (Ubuntu 20.04 KDE)

Pastebin of error produced: https://pastebin.com/kDryLVZn
